export const ADD_COURSE_EDUCATION = "ADD_COURSE_EDUCATION"; //adding Education.
export const GET_ALL_EDUCATION = "GET_ALL_EDUCATION";
export const GET_EDUCATION_BY_ID = "GET_EDUCATION_BY_ID";
export const UPDATE_EDUCATION_BY_ID = "UPDATE_EDUCATION_BY_ID";
